### ISSUE TITLE
PDF Styling: broken style of line breaks in lists

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/safetag-web#86]
Some lists in the PDF output have broken styles:

![Screenshot 2020-10-16 at 11 11 18](https://user-images.githubusercontent.com/329694/96246375-73fbd500-0fa0-11eb-982b-d6fba51722c0.png)

This is happening because some sections contents in frontmatter have `\n` instead of line breaks. This is a problem in the migration script.

**Comment by LanesGood** [comment]
@vgeorge this seems to be due to #137

**Comment by LanesGood** [comment]
Closed by #138
